
package br.ifirst.tissapi.ws;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "tissCancelaGuia", targetNamespace = "http://www.ans.gov.br/tiss/ws/tipos/tisscancelaguia/v30302", wsdlLocation = "tissCancelaGuiaV3_03_02.wsdl")
public class TissCancelaGuia
    extends Service
{

    private final static URL TISSCANCELAGUIA_WSDL_LOCATION;
    private final static WebServiceException TISSCANCELAGUIA_EXCEPTION;
    private final static QName TISSCANCELAGUIA_QNAME = new QName("http://www.ans.gov.br/tiss/ws/tipos/tisscancelaguia/v30302", "tissCancelaGuia");

    static {
        TISSCANCELAGUIA_WSDL_LOCATION = br.ifirst.tissapi.ws.TissCancelaGuia.class.getResource("tissCancelaGuiaV3_03_02.wsdl");
        WebServiceException e = null;
        if (TISSCANCELAGUIA_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'tissCancelaGuiaV3_03_02.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        TISSCANCELAGUIA_EXCEPTION = e;
    }

    public TissCancelaGuia() {
        super(__getWsdlLocation(), TISSCANCELAGUIA_QNAME);
    }

    public TissCancelaGuia(WebServiceFeature... features) {
        super(__getWsdlLocation(), TISSCANCELAGUIA_QNAME, features);
    }

    public TissCancelaGuia(URL wsdlLocation) {
        super(wsdlLocation, TISSCANCELAGUIA_QNAME);
    }

    public TissCancelaGuia(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TISSCANCELAGUIA_QNAME, features);
    }

    public TissCancelaGuia(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TissCancelaGuia(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TissCancelaGuiaPortType
     */
    @WebEndpoint(name = "tissCancelaGuia_Port")
    public TissCancelaGuiaPortType getTissCancelaGuiaPort() {
        return super.getPort(new QName("http://www.ans.gov.br/tiss/ws/tipos/tisscancelaguia/v30302", "tissCancelaGuia_Port"), TissCancelaGuiaPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TissCancelaGuiaPortType
     */
    @WebEndpoint(name = "tissCancelaGuia_Port")
    public TissCancelaGuiaPortType getTissCancelaGuiaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ans.gov.br/tiss/ws/tipos/tisscancelaguia/v30302", "tissCancelaGuia_Port"), TissCancelaGuiaPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TISSCANCELAGUIA_EXCEPTION!= null) {
            throw TISSCANCELAGUIA_EXCEPTION;
        }
        return TISSCANCELAGUIA_WSDL_LOCATION;
    }

}
