
package br.ifirst.tissapi.ws;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "tissSolicitacaoStatusAutorizacao", targetNamespace = "http://www.ans.gov.br/tiss/ws/tipos/tisssolicitacaostatusautorizacao/v30302", wsdlLocation = "tissSolicitacaoStatusAutorizacaoV3_03_02.wsdl")
public class TissSolicitacaoStatusAutorizacao
    extends Service
{

    private final static URL TISSSOLICITACAOSTATUSAUTORIZACAO_WSDL_LOCATION;
    private final static WebServiceException TISSSOLICITACAOSTATUSAUTORIZACAO_EXCEPTION;
    private final static QName TISSSOLICITACAOSTATUSAUTORIZACAO_QNAME = new QName("http://www.ans.gov.br/tiss/ws/tipos/tisssolicitacaostatusautorizacao/v30302", "tissSolicitacaoStatusAutorizacao");

    static {
        TISSSOLICITACAOSTATUSAUTORIZACAO_WSDL_LOCATION = br.ifirst.tissapi.ws.TissSolicitacaoStatusAutorizacao.class.getResource("tissSolicitacaoStatusAutorizacaoV3_03_02.wsdl");
        WebServiceException e = null;
        if (TISSSOLICITACAOSTATUSAUTORIZACAO_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'tissSolicitacaoStatusAutorizacaoV3_03_02.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        TISSSOLICITACAOSTATUSAUTORIZACAO_EXCEPTION = e;
    }

    public TissSolicitacaoStatusAutorizacao() {
        super(__getWsdlLocation(), TISSSOLICITACAOSTATUSAUTORIZACAO_QNAME);
    }

    public TissSolicitacaoStatusAutorizacao(WebServiceFeature... features) {
        super(__getWsdlLocation(), TISSSOLICITACAOSTATUSAUTORIZACAO_QNAME, features);
    }

    public TissSolicitacaoStatusAutorizacao(URL wsdlLocation) {
        super(wsdlLocation, TISSSOLICITACAOSTATUSAUTORIZACAO_QNAME);
    }

    public TissSolicitacaoStatusAutorizacao(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TISSSOLICITACAOSTATUSAUTORIZACAO_QNAME, features);
    }

    public TissSolicitacaoStatusAutorizacao(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TissSolicitacaoStatusAutorizacao(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TissSolicitacaoStatusAutorizacaoPortType
     */
    @WebEndpoint(name = "tissSolicitacaoStatusAutorizacao_Port")
    public TissSolicitacaoStatusAutorizacaoPortType getTissSolicitacaoStatusAutorizacaoPort() {
        return super.getPort(new QName("http://www.ans.gov.br/tiss/ws/tipos/tisssolicitacaostatusautorizacao/v30302", "tissSolicitacaoStatusAutorizacao_Port"), TissSolicitacaoStatusAutorizacaoPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TissSolicitacaoStatusAutorizacaoPortType
     */
    @WebEndpoint(name = "tissSolicitacaoStatusAutorizacao_Port")
    public TissSolicitacaoStatusAutorizacaoPortType getTissSolicitacaoStatusAutorizacaoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ans.gov.br/tiss/ws/tipos/tisssolicitacaostatusautorizacao/v30302", "tissSolicitacaoStatusAutorizacao_Port"), TissSolicitacaoStatusAutorizacaoPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TISSSOLICITACAOSTATUSAUTORIZACAO_EXCEPTION!= null) {
            throw TISSSOLICITACAOSTATUSAUTORIZACAO_EXCEPTION;
        }
        return TISSSOLICITACAOSTATUSAUTORIZACAO_WSDL_LOCATION;
    }

}
