
package br.ifirst.tissapi.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "tissSolicitacaoStatusAutorizacao_PortType", targetNamespace = "http://www.ans.gov.br/tiss/ws/tipos/tisssolicitacaostatusautorizacao/v30302")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TissSolicitacaoStatusAutorizacaoPortType {


    /**
     * 
     * @param solicitacaoStatusAutorizacao
     * @return
     *     returns br.ifirst.tissapi.ws.SituacaoAutorizacaoWS
     * @throws TissFault
     */
    @WebMethod(operationName = "tissSolicitacaoStatusAutorizacao_Operation")
    @WebResult(name = "situacaoAutorizacaoWS", targetNamespace = "http://www.ans.gov.br/padroes/tiss/schemas", partName = "situacaoAutorizacao")
    public SituacaoAutorizacaoWS tissSolicitacaoStatusAutorizacaoOperation(
        @WebParam(name = "solicitacaoStatusAutorizacaoWS", targetNamespace = "http://www.ans.gov.br/padroes/tiss/schemas", partName = "solicitacaoStatusAutorizacao")
        SolicitacaoStatusAutorizacaoWS solicitacaoStatusAutorizacao)
        throws TissFault
    ;

}
