
package br.ifirst.tissapi.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "tissFaultWS", targetNamespace = "http://www.ans.gov.br/padroes/tiss/schemas")
public class TissFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private TissFaultWS faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public TissFault(String message, TissFaultWS faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public TissFault(String message, TissFaultWS faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: br.ifirst.tissapi.ws.TissFaultWS
     */
    public TissFaultWS getFaultInfo() {
        return faultInfo;
    }

}
