
package br.ifirst.tissapi.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "tissVerificaElegibilidade_PortType", targetNamespace = "http://www.ans.gov.br/tiss/ws/tipos/tissverificaelegibilidade/v30302")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TissVerificaElegibilidadePortType {


    /**
     * 
     * @param pedidoElegibilidade
     * @return
     *     returns br.ifirst.tissapi.ws.RespostaElegibilidadeWS
     * @throws TissFault
     */
    @WebMethod(operationName = "tissVerificaElegibilidade_Operation")
    @WebResult(name = "respostaElegibilidadeWS", targetNamespace = "http://www.ans.gov.br/padroes/tiss/schemas", partName = "respostaElegibilidade")
    public RespostaElegibilidadeWS tissVerificaElegibilidadeOperation(
        @WebParam(name = "pedidoElegibilidadeWS", targetNamespace = "http://www.ans.gov.br/padroes/tiss/schemas", partName = "pedidoElegibilidade")
        PedidoElegibilidadeWS pedidoElegibilidade)
        throws TissFault
    ;

}
