
package br.ifirst.tissapi.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "tissLoteGuias_PortType", targetNamespace = "http://www.ans.gov.br/tiss/ws/tipos/tissloteguias/v30302")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TissLoteGuiasPortType {


    /**
     * 
     * @param loteGuias
     * @return
     *     returns br.ifirst.tissapi.ws.ProtocoloRecebimentoWS
     * @throws TissFault
     */
    @WebMethod(operationName = "tissLoteGuias_Operation")
    @WebResult(name = "protocoloRecebimentoWS", targetNamespace = "http://www.ans.gov.br/padroes/tiss/schemas", partName = "protocoloRecebimento")
    public ProtocoloRecebimentoWS tissLoteGuiasOperation(
        @WebParam(name = "loteGuiasWS", targetNamespace = "http://www.ans.gov.br/padroes/tiss/schemas", partName = "loteGuias")
        LoteGuiasWS loteGuias)
        throws TissFault
    ;

}
