
package br.ifirst.tissapi.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "tissSolicitacaoProcedimento_PortType", targetNamespace = "http://www.ans.gov.br/tiss/ws/tipos/tisssolicitacaoprocedimento/v30302")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TissSolicitacaoProcedimentoPortType {


    /**
     * 
     * @param solicitacaoProcedimento
     * @return
     *     returns br.ifirst.tissapi.ws.AutorizacaoProcedimentoWS
     * @throws TissFault
     */
    @WebMethod(operationName = "tissSolicitacaoProcedimento_Operation")
    @WebResult(name = "autorizacaoProcedimentoWS", targetNamespace = "http://www.ans.gov.br/padroes/tiss/schemas", partName = "autorizacaoProcedimento")
    public AutorizacaoProcedimentoWS tissSolicitacaoProcedimentoOperation(
        @WebParam(name = "solicitacaoProcedimentoWS", targetNamespace = "http://www.ans.gov.br/padroes/tiss/schemas", partName = "solicitacaoProcedimento")
        SolicitacaoProcedimentoWS solicitacaoProcedimento)
        throws TissFault
    ;

}
