
package br.ifirst.tissapi.ws;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "tissLoteGuias", targetNamespace = "http://www.ans.gov.br/tiss/ws/tipos/tissloteguias/v30302", wsdlLocation = "C:\\Users\\itecbrazil\\Documents\\NetBeansProjects\\TissApi/src/main/resources/schematiss/v3_03_03/tissLoteGuiasV3_03_02.wsdl")
public class TissLoteGuias
    extends Service
{

    private final static URL TISSLOTEGUIAS_WSDL_LOCATION;
    private final static WebServiceException TISSLOTEGUIAS_EXCEPTION;
    private final static QName TISSLOTEGUIAS_QNAME = new QName("http://www.ans.gov.br/tiss/ws/tipos/tissloteguias/v30302", "tissLoteGuias");

    static {
        TISSLOTEGUIAS_WSDL_LOCATION = br.ifirst.tissapi.ws.TissLoteGuias.class.getResource("C:\\Users\\itecbrazil\\Documents\\NetBeansProjects\\TissApi/src/main/resources/schematiss/v3_03_03/tissLoteGuiasV3_03_02.wsdl");
        WebServiceException e = null;
        if (TISSLOTEGUIAS_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'C:\\\\Users\\\\itecbrazil\\\\Documents\\\\NetBeansProjects\\\\TissApi/src/main/resources/schematiss/v3_03_03/tissLoteGuiasV3_03_02.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        TISSLOTEGUIAS_EXCEPTION = e;
    }

    public TissLoteGuias() {
        super(__getWsdlLocation(), TISSLOTEGUIAS_QNAME);
    }

    public TissLoteGuias(WebServiceFeature... features) {
        super(__getWsdlLocation(), TISSLOTEGUIAS_QNAME, features);
    }

    public TissLoteGuias(URL wsdlLocation) {
        super(wsdlLocation, TISSLOTEGUIAS_QNAME);
    }

    public TissLoteGuias(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TISSLOTEGUIAS_QNAME, features);
    }

    public TissLoteGuias(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TissLoteGuias(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TissLoteGuiasPortType
     */
    @WebEndpoint(name = "tissLoteGuias_Port")
    public TissLoteGuiasPortType getTissLoteGuiasPort() {
        return super.getPort(new QName("http://www.ans.gov.br/tiss/ws/tipos/tissloteguias/v30302", "tissLoteGuias_Port"), TissLoteGuiasPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TissLoteGuiasPortType
     */
    @WebEndpoint(name = "tissLoteGuias_Port")
    public TissLoteGuiasPortType getTissLoteGuiasPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ans.gov.br/tiss/ws/tipos/tissloteguias/v30302", "tissLoteGuias_Port"), TissLoteGuiasPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TISSLOTEGUIAS_EXCEPTION!= null) {
            throw TISSLOTEGUIAS_EXCEPTION;
        }
        return TISSLOTEGUIAS_WSDL_LOCATION;
    }

}
