
package br.ifirst.tissapi.ws;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "tissSolicitacaoProcedimento", targetNamespace = "http://www.ans.gov.br/tiss/ws/tipos/tisssolicitacaoprocedimento/v30302", wsdlLocation = "tissSolicitacaoProcedimentoV3_03_02.wsdl")
public class TissSolicitacaoProcedimento
    extends Service
{

    private final static URL TISSSOLICITACAOPROCEDIMENTO_WSDL_LOCATION;
    private final static WebServiceException TISSSOLICITACAOPROCEDIMENTO_EXCEPTION;
    private final static QName TISSSOLICITACAOPROCEDIMENTO_QNAME = new QName("http://www.ans.gov.br/tiss/ws/tipos/tisssolicitacaoprocedimento/v30302", "tissSolicitacaoProcedimento");

    static {
        TISSSOLICITACAOPROCEDIMENTO_WSDL_LOCATION = br.ifirst.tissapi.ws.TissSolicitacaoProcedimento.class.getResource("tissSolicitacaoProcedimentoV3_03_02.wsdl");
        WebServiceException e = null;
        if (TISSSOLICITACAOPROCEDIMENTO_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'tissSolicitacaoProcedimentoV3_03_02.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        TISSSOLICITACAOPROCEDIMENTO_EXCEPTION = e;
    }

    public TissSolicitacaoProcedimento() {
        super(__getWsdlLocation(), TISSSOLICITACAOPROCEDIMENTO_QNAME);
    }

    public TissSolicitacaoProcedimento(WebServiceFeature... features) {
        super(__getWsdlLocation(), TISSSOLICITACAOPROCEDIMENTO_QNAME, features);
    }

    public TissSolicitacaoProcedimento(URL wsdlLocation) {
        super(wsdlLocation, TISSSOLICITACAOPROCEDIMENTO_QNAME);
    }

    public TissSolicitacaoProcedimento(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TISSSOLICITACAOPROCEDIMENTO_QNAME, features);
    }

    public TissSolicitacaoProcedimento(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TissSolicitacaoProcedimento(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TissSolicitacaoProcedimentoPortType
     */
    @WebEndpoint(name = "tissSolicitacaoProcedimento_Port")
    public TissSolicitacaoProcedimentoPortType getTissSolicitacaoProcedimentoPort() {
        return super.getPort(new QName("http://www.ans.gov.br/tiss/ws/tipos/tisssolicitacaoprocedimento/v30302", "tissSolicitacaoProcedimento_Port"), TissSolicitacaoProcedimentoPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TissSolicitacaoProcedimentoPortType
     */
    @WebEndpoint(name = "tissSolicitacaoProcedimento_Port")
    public TissSolicitacaoProcedimentoPortType getTissSolicitacaoProcedimentoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ans.gov.br/tiss/ws/tipos/tisssolicitacaoprocedimento/v30302", "tissSolicitacaoProcedimento_Port"), TissSolicitacaoProcedimentoPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TISSSOLICITACAOPROCEDIMENTO_EXCEPTION!= null) {
            throw TISSSOLICITACAOPROCEDIMENTO_EXCEPTION;
        }
        return TISSSOLICITACAOPROCEDIMENTO_WSDL_LOCATION;
    }

}
