
package br.ifirst.tissapi.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "tissCancelaGuia_PortType", targetNamespace = "http://www.ans.gov.br/tiss/ws/tipos/tisscancelaguia/v30302")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TissCancelaGuiaPortType {


    /**
     * 
     * @param cancelaGuia
     * @return
     *     returns br.ifirst.tissapi.ws.ReciboCancelaGuiaWS
     * @throws TissFault
     */
    @WebMethod(operationName = "tissCancelaGuia_Operation")
    @WebResult(name = "reciboCancelaGuiaWS", targetNamespace = "http://www.ans.gov.br/padroes/tiss/schemas", partName = "reciboCancelaGuia")
    public ReciboCancelaGuiaWS tissCancelaGuiaOperation(
        @WebParam(name = "cancelaGuiaWS", targetNamespace = "http://www.ans.gov.br/padroes/tiss/schemas", partName = "cancelaGuia")
        CancelaGuiaWS cancelaGuia)
        throws TissFault
    ;

}
